[package]
name = "vxdraw"
version = "0.1.0"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.4"
cgmath = "0.17"
gfx-backend-dx12 = { version = "0.2", optional = true }
gfx-backend-gl = { version = "0.2", optional = true }
gfx-backend-metal = { version = "0.2", optional = true }
gfx-backend-vulkan = { version = "0.2", optional = true }
gfx-hal = "0.2"
glsl-to-spirv = "0.1.4"
glutin = { version = "0.20", optional = true }
image = "0.21"
rand = "0.6.1"
rand_pcg = "0.1.2"
winit = "0.19"

logger = { path = "../logger" }

[dev-dependencies]
itertools = "0.8"

[features]
default = ["vulkan"]
dev = []
dx12 = ["gfx-backend-dx12"]
gl = ["gfx-backend-gl", "glutin"]
metal = ["gfx-backend-metal"]
vulkan = ["gfx-backend-vulkan"]
